In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [17]:
data=pd.read_csv("C:/Users/VISHNU A M/Downloads/room.csv")
data

area  bedrooms  age  price
0  3000       4.0   18  68000
1  3200       4.0   18  72000
2  3400       4.0   20  76000
3  3600       NaN   55  80000
4  3800       4.0   20  84000
5  4000       4.0   24  88000
6  4200       4.0   25  92000

In [18]:
import math
median_bed=math.floor(data.bedrooms.median())
median_bed

4

In [19]:
data.bedrooms =data.bedrooms.fillna(median_bed)
data

area  bedrooms  age  price
0  3000       4.0   18  68000
1  3200       4.0   18  72000
2  3400       4.0   20  76000
3  3600       4.0   55  80000
4  3800       4.0   20  84000
5  4000       4.0   24  88000
6  4200       4.0   25  92000

In [20]:
regress=linear_model.LinearRegression()
regress.fit(data[['area','bedrooms','age']],data.price)

LinearRegression()

In [21]:
#coef values (m), y=m1x+m2x+...+b
regress.coef_

array([2.00000000e+01, 0.00000000e+00, 1.25551758e-14])

In [22]:
#intercet value (b),y=mx+b
regress.intercept_

8000.000000000029

In [24]:
#prediction values
regress.predict([[3800,4,20]])

C:\Users\VISHNU A M\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([84000.])

In [25]:
regress.predict([[2800,6,20]])

C:\Users\VISHNU A M\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([64000.])